### ISSUE TITLE
Remove TMP

### ISSUE THREAD

**Issue by MarisaKirisame** [MarisaKirisame/first_order_logic_prover#19]
use boost::mpl

**Comment by FrankHB** [comment]
I don't think use of `mpl` is a good trend. For readability and ease of maintenance, they'd better be replaced by variadic template based techniques ... much like the current state, though there might be other issues, e.g. to use `std::conditional_t` instead of `std::conditional` which should be always possible under C++14.

**Comment by lolisa** [comment]
Yeah, you are correct on this. So I am looking at boost::hana because it claim to be boost::mpl in C++14. Also, thx for the std::conditional_t part, I'll check.
